"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false
command_timeout = 1000

format = """
$directory\
$git_branch\
$git_status\
$python\
$nodejs\
$cmd_duration\
$line_break\
$character"""

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"

[directory]
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = true   
style = "bold cyan"       

[git_branch]
symbol = " "      
style = "bold purple"

[git_status]
format = '[\($all_status$ahead_behind\)]($style)'
conflicted = "🏳"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"

[nodejs]
format = "via [⬢ $version](green) "

[python]
disabled = true

[cmd_duration]
format = "took [$duration](yellow) "
min_time = 1000